version: '3.5'

services:
  node:
    build: .
    volumes: 
      - ./data:/data
    ports:
      - "9000-9009:9984"
      - "9010-9019:9985"
      # - "26656:26656"
      # - "26658:26658"
    environment:
      - BIGCHAINDB_SERVER_BIND=0.0.0.0:9984
      - BIGCHAINDB_WSSERVER_HOST=0.0.0.0
      - BIGCHAINDB_TENDERMINT_HOST=0.0.0.0
      - BIGCHAINDB_TENDERMINT_PORT=26657
      - BIGCHAINDB_WSSERVER_ADVERTISED_HOS=0.0.0.0

